site_name: Machines
site_description: Portafolio de máquinas y writeups de ciberseguridad
site_author: Gabriel Saavedra
site_url: https://gaabooox.github.io/Machines/

repo_name: Gaabooox/Machines
repo_url: https://github.com/Gaabooox/Machines

nav:
  - Inicio: index.md
  - Máquinas: machines/index.md
  - Sobre mí: about.md

not_in_nav: |
  dockerlabs/**/*.md
  hackthebox/**/*.md
  tryhackme/**/*.md
  vulnhub/**/*.md

theme:
  name: material
  language: es

  icon:
    logo: fontawesome/solid/skull
    repo: fontawesome/brands/github

  palette:
    scheme: slate

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

extra_css:
  - stylesheets/extra.css
  - stylesheets/catalog.css
  - stylesheets/about.css

extra_javascript:
  - javascripts/machines.js
  - javascripts/home.js
